stages:
  - test
  - deploy

test-rust:
  stage: test
  tags:
    - m5
  image: rust:1.96-slim
  script:
    - apt-get update && apt-get install -y protobuf-compiler
    - cargo test --workspace
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "test"'

deploy-site-test:
  stage: deploy
  tags:
    - m5
  image: google/cloud-sdk:alpine
  rules:
    - if: '$CI_COMMIT_BRANCH == "test"'
  script:
    - chmod +x deploy_wasmee_site.sh
    - ./deploy_wasmee_site.sh test

deploy-site-main:
  stage: deploy
  tags:
    - m5
  image: google/cloud-sdk:alpine
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - chmod +x deploy_wasmee_site.sh
    - ./deploy_wasmee_site.sh prod
