// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/wasmee.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ExecuteMessage_Start
	//	*ExecuteMessage_HostCallRequest
	//	*ExecuteMessage_HostCallResponse
	//	*ExecuteMessage_Checkpoint
	//	*ExecuteMessage_CheckpointResponse
	//	*ExecuteMessage_Complete
	Message       isExecuteMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteMessage) Reset() {
	*x = ExecuteMessage{}
	mi := &file_proto_wasmee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteMessage) ProtoMessage() {}

func (x *ExecuteMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteMessage.ProtoReflect.Descriptor instead.
func (*ExecuteMessage) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteMessage) GetMessage() isExecuteMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ExecuteMessage) GetStart() *StartRequest {
	if x != nil {
		if x, ok := x.Message.(*ExecuteMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecuteMessage) GetHostCallRequest() *HostCallRequest {
	if x != nil {
		if x, ok := x.Message.(*ExecuteMessage_HostCallRequest); ok {
			return x.HostCallRequest
		}
	}
	return nil
}

func (x *ExecuteMessage) GetHostCallResponse() *HostCallResponse {
	if x != nil {
		if x, ok := x.Message.(*ExecuteMessage_HostCallResponse); ok {
			return x.HostCallResponse
		}
	}
	return nil
}

func (x *ExecuteMessage) GetCheckpoint() *CheckpointRequest {
	if x != nil {
		if x, ok := x.Message.(*ExecuteMessage_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

func (x *ExecuteMessage) GetCheckpointResponse() *CheckpointResponse {
	if x != nil {
		if x, ok := x.Message.(*ExecuteMessage_CheckpointResponse); ok {
			return x.CheckpointResponse
		}
	}
	return nil
}

func (x *ExecuteMessage) GetComplete() *CompleteResponse {
	if x != nil {
		if x, ok := x.Message.(*ExecuteMessage_Complete); ok {
			return x.Complete
		}
	}
	return nil
}

type isExecuteMessage_Message interface {
	isExecuteMessage_Message()
}

type ExecuteMessage_Start struct {
	Start *StartRequest `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecuteMessage_HostCallRequest struct {
	HostCallRequest *HostCallRequest `protobuf:"bytes,2,opt,name=host_call_request,json=hostCallRequest,proto3,oneof"`
}

type ExecuteMessage_HostCallResponse struct {
	HostCallResponse *HostCallResponse `protobuf:"bytes,3,opt,name=host_call_response,json=hostCallResponse,proto3,oneof"`
}

type ExecuteMessage_Checkpoint struct {
	Checkpoint *CheckpointRequest `protobuf:"bytes,4,opt,name=checkpoint,proto3,oneof"`
}

type ExecuteMessage_CheckpointResponse struct {
	CheckpointResponse *CheckpointResponse `protobuf:"bytes,5,opt,name=checkpoint_response,json=checkpointResponse,proto3,oneof"`
}

type ExecuteMessage_Complete struct {
	Complete *CompleteResponse `protobuf:"bytes,6,opt,name=complete,proto3,oneof"`
}

func (*ExecuteMessage_Start) isExecuteMessage_Message() {}

func (*ExecuteMessage_HostCallRequest) isExecuteMessage_Message() {}

func (*ExecuteMessage_HostCallResponse) isExecuteMessage_Message() {}

func (*ExecuteMessage_Checkpoint) isExecuteMessage_Message() {}

func (*ExecuteMessage_CheckpointResponse) isExecuteMessage_Message() {}

func (*ExecuteMessage_Complete) isExecuteMessage_Message() {}

type OplogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallIndex       int32                  `protobuf:"varint,1,opt,name=call_index,json=callIndex,proto3" json:"call_index,omitempty"`
	ApiName         string                 `protobuf:"bytes,2,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	RequestPayload  []byte                 `protobuf:"bytes,3,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	ResponsePayload []byte                 `protobuf:"bytes,4,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OplogEntry) Reset() {
	*x = OplogEntry{}
	mi := &file_proto_wasmee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OplogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OplogEntry) ProtoMessage() {}

func (x *OplogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OplogEntry.ProtoReflect.Descriptor instead.
func (*OplogEntry) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{1}
}

func (x *OplogEntry) GetCallIndex() int32 {
	if x != nil {
		return x.CallIndex
	}
	return 0
}

func (x *OplogEntry) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *OplogEntry) GetRequestPayload() []byte {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *OplogEntry) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

type StartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	WasmBytes     []byte                 `protobuf:"bytes,2,opt,name=wasm_bytes,json=wasmBytes,proto3" json:"wasm_bytes,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,3,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Params        []uint64               `protobuf:"varint,4,rep,packed,name=params,proto3" json:"params,omitempty"`
	BaseSnapshot  []byte                 `protobuf:"bytes,5,opt,name=base_snapshot,json=baseSnapshot,proto3" json:"base_snapshot,omitempty"`
	MemoryDeltas  map[int32][]byte       `protobuf:"bytes,6,rep,name=memory_deltas,json=memoryDeltas,proto3" json:"memory_deltas,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Oplog         []*OplogEntry          `protobuf:"bytes,7,rep,name=oplog,proto3" json:"oplog,omitempty"`
	CallIndex     int32                  `protobuf:"varint,8,opt,name=call_index,json=callIndex,proto3" json:"call_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRequest) Reset() {
	*x = StartRequest{}
	mi := &file_proto_wasmee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRequest) ProtoMessage() {}

func (x *StartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRequest.ProtoReflect.Descriptor instead.
func (*StartRequest) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{2}
}

func (x *StartRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartRequest) GetWasmBytes() []byte {
	if x != nil {
		return x.WasmBytes
	}
	return nil
}

func (x *StartRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *StartRequest) GetParams() []uint64 {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *StartRequest) GetBaseSnapshot() []byte {
	if x != nil {
		return x.BaseSnapshot
	}
	return nil
}

func (x *StartRequest) GetMemoryDeltas() map[int32][]byte {
	if x != nil {
		return x.MemoryDeltas
	}
	return nil
}

func (x *StartRequest) GetOplog() []*OplogEntry {
	if x != nil {
		return x.Oplog
	}
	return nil
}

func (x *StartRequest) GetCallIndex() int32 {
	if x != nil {
		return x.CallIndex
	}
	return 0
}

type HostCallRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ApiName        string                 `protobuf:"bytes,1,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	RequestPayload []byte                 `protobuf:"bytes,2,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	CallIndex      int32                  `protobuf:"varint,3,opt,name=call_index,json=callIndex,proto3" json:"call_index,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HostCallRequest) Reset() {
	*x = HostCallRequest{}
	mi := &file_proto_wasmee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCallRequest) ProtoMessage() {}

func (x *HostCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCallRequest.ProtoReflect.Descriptor instead.
func (*HostCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{3}
}

func (x *HostCallRequest) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *HostCallRequest) GetRequestPayload() []byte {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *HostCallRequest) GetCallIndex() int32 {
	if x != nil {
		return x.CallIndex
	}
	return 0
}

type HostCallResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ResponsePayload []byte                 `protobuf:"bytes,1,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HostCallResponse) Reset() {
	*x = HostCallResponse{}
	mi := &file_proto_wasmee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostCallResponse) ProtoMessage() {}

func (x *HostCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostCallResponse.ProtoReflect.Descriptor instead.
func (*HostCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{4}
}

func (x *HostCallResponse) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

func (x *HostCallResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentMemory []byte                 `protobuf:"bytes,1,opt,name=current_memory,json=currentMemory,proto3" json:"current_memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointRequest) Reset() {
	*x = CheckpointRequest{}
	mi := &file_proto_wasmee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointRequest) ProtoMessage() {}

func (x *CheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointRequest.ProtoReflect.Descriptor instead.
func (*CheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{5}
}

func (x *CheckpointRequest) GetCurrentMemory() []byte {
	if x != nil {
		return x.CurrentMemory
	}
	return nil
}

type CheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_proto_wasmee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{6}
}

func (x *CheckpointResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crashed       bool                   `protobuf:"varint,1,opt,name=crashed,proto3" json:"crashed,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FinalDeltas   map[int32][]byte       `protobuf:"bytes,3,rep,name=final_deltas,json=finalDeltas,proto3" json:"final_deltas,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FinalOplog    []*OplogEntry          `protobuf:"bytes,4,rep,name=final_oplog,json=finalOplog,proto3" json:"final_oplog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteResponse) Reset() {
	*x = CompleteResponse{}
	mi := &file_proto_wasmee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteResponse) ProtoMessage() {}

func (x *CompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wasmee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteResponse.ProtoReflect.Descriptor instead.
func (*CompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_wasmee_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteResponse) GetCrashed() bool {
	if x != nil {
		return x.Crashed
	}
	return false
}

func (x *CompleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompleteResponse) GetFinalDeltas() map[int32][]byte {
	if x != nil {
		return x.FinalDeltas
	}
	return nil
}

func (x *CompleteResponse) GetFinalOplog() []*OplogEntry {
	if x != nil {
		return x.FinalOplog
	}
	return nil
}

var File_proto_wasmee_proto protoreflect.FileDescriptor

const file_proto_wasmee_proto_rawDesc = "" +
	"\n" +
	"\x12proto/wasmee.proto\x12\x06wasmee\"\x9e\x03\n" +
	"\x0eExecuteMessage\x12,\n" +
	"\x05start\x18\x01 \x01(\v2\x14.wasmee.StartRequestH\x00R\x05start\x12E\n" +
	"\x11host_call_request\x18\x02 \x01(\v2\x17.wasmee.HostCallRequestH\x00R\x0fhostCallRequest\x12H\n" +
	"\x12host_call_response\x18\x03 \x01(\v2\x18.wasmee.HostCallResponseH\x00R\x10hostCallResponse\x12;\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\v2\x19.wasmee.CheckpointRequestH\x00R\n" +
	"checkpoint\x12M\n" +
	"\x13checkpoint_response\x18\x05 \x01(\v2\x1a.wasmee.CheckpointResponseH\x00R\x12checkpointResponse\x126\n" +
	"\bcomplete\x18\x06 \x01(\v2\x18.wasmee.CompleteResponseH\x00R\bcompleteB\t\n" +
	"\amessage\"\x9a\x01\n" +
	"\n" +
	"OplogEntry\x12\x1d\n" +
	"\n" +
	"call_index\x18\x01 \x01(\x05R\tcallIndex\x12\x19\n" +
	"\bapi_name\x18\x02 \x01(\tR\aapiName\x12'\n" +
	"\x0frequest_payload\x18\x03 \x01(\fR\x0erequestPayload\x12)\n" +
	"\x10response_payload\x18\x04 \x01(\fR\x0fresponsePayload\"\x82\x03\n" +
	"\fStartRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1d\n" +
	"\n" +
	"wasm_bytes\x18\x02 \x01(\fR\twasmBytes\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x03 \x01(\tR\n" +
	"entrypoint\x12\x16\n" +
	"\x06params\x18\x04 \x03(\x04R\x06params\x12#\n" +
	"\rbase_snapshot\x18\x05 \x01(\fR\fbaseSnapshot\x12K\n" +
	"\rmemory_deltas\x18\x06 \x03(\v2&.wasmee.StartRequest.MemoryDeltasEntryR\fmemoryDeltas\x12(\n" +
	"\x05oplog\x18\a \x03(\v2\x12.wasmee.OplogEntryR\x05oplog\x12\x1d\n" +
	"\n" +
	"call_index\x18\b \x01(\x05R\tcallIndex\x1a?\n" +
	"\x11MemoryDeltasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"t\n" +
	"\x0fHostCallRequest\x12\x19\n" +
	"\bapi_name\x18\x01 \x01(\tR\aapiName\x12'\n" +
	"\x0frequest_payload\x18\x02 \x01(\fR\x0erequestPayload\x12\x1d\n" +
	"\n" +
	"call_index\x18\x03 \x01(\x05R\tcallIndex\"S\n" +
	"\x10HostCallResponse\x12)\n" +
	"\x10response_payload\x18\x01 \x01(\fR\x0fresponsePayload\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\x11CheckpointRequest\x12%\n" +
	"\x0ecurrent_memory\x18\x01 \x01(\fR\rcurrentMemory\"*\n" +
	"\x12CheckpointResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x85\x02\n" +
	"\x10CompleteResponse\x12\x18\n" +
	"\acrashed\x18\x01 \x01(\bR\acrashed\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12L\n" +
	"\ffinal_deltas\x18\x03 \x03(\v2).wasmee.CompleteResponse.FinalDeltasEntryR\vfinalDeltas\x123\n" +
	"\vfinal_oplog\x18\x04 \x03(\v2\x12.wasmee.OplogEntryR\n" +
	"finalOplog\x1a>\n" +
	"\x10FinalDeltasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x012O\n" +
	"\x0eWasmeeExecutor\x12=\n" +
	"\aExecute\x12\x16.wasmee.ExecuteMessage\x1a\x16.wasmee.ExecuteMessage(\x010\x01B#Z!gitlab.com/nativebpm/wasmee/protob\x06proto3"

var (
	file_proto_wasmee_proto_rawDescOnce sync.Once
	file_proto_wasmee_proto_rawDescData []byte
)

func file_proto_wasmee_proto_rawDescGZIP() []byte {
	file_proto_wasmee_proto_rawDescOnce.Do(func() {
		file_proto_wasmee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wasmee_proto_rawDesc), len(file_proto_wasmee_proto_rawDesc)))
	})
	return file_proto_wasmee_proto_rawDescData
}

var file_proto_wasmee_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_wasmee_proto_goTypes = []any{
	(*ExecuteMessage)(nil),     // 0: wasmee.ExecuteMessage
	(*OplogEntry)(nil),         // 1: wasmee.OplogEntry
	(*StartRequest)(nil),       // 2: wasmee.StartRequest
	(*HostCallRequest)(nil),    // 3: wasmee.HostCallRequest
	(*HostCallResponse)(nil),   // 4: wasmee.HostCallResponse
	(*CheckpointRequest)(nil),  // 5: wasmee.CheckpointRequest
	(*CheckpointResponse)(nil), // 6: wasmee.CheckpointResponse
	(*CompleteResponse)(nil),   // 7: wasmee.CompleteResponse
	nil,                        // 8: wasmee.StartRequest.MemoryDeltasEntry
	nil,                        // 9: wasmee.CompleteResponse.FinalDeltasEntry
}
var file_proto_wasmee_proto_depIdxs = []int32{
	2,  // 0: wasmee.ExecuteMessage.start:type_name -> wasmee.StartRequest
	3,  // 1: wasmee.ExecuteMessage.host_call_request:type_name -> wasmee.HostCallRequest
	4,  // 2: wasmee.ExecuteMessage.host_call_response:type_name -> wasmee.HostCallResponse
	5,  // 3: wasmee.ExecuteMessage.checkpoint:type_name -> wasmee.CheckpointRequest
	6,  // 4: wasmee.ExecuteMessage.checkpoint_response:type_name -> wasmee.CheckpointResponse
	7,  // 5: wasmee.ExecuteMessage.complete:type_name -> wasmee.CompleteResponse
	8,  // 6: wasmee.StartRequest.memory_deltas:type_name -> wasmee.StartRequest.MemoryDeltasEntry
	1,  // 7: wasmee.StartRequest.oplog:type_name -> wasmee.OplogEntry
	9,  // 8: wasmee.CompleteResponse.final_deltas:type_name -> wasmee.CompleteResponse.FinalDeltasEntry
	1,  // 9: wasmee.CompleteResponse.final_oplog:type_name -> wasmee.OplogEntry
	0,  // 10: wasmee.WasmeeExecutor.Execute:input_type -> wasmee.ExecuteMessage
	0,  // 11: wasmee.WasmeeExecutor.Execute:output_type -> wasmee.ExecuteMessage
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_wasmee_proto_init() }
func file_proto_wasmee_proto_init() {
	if File_proto_wasmee_proto != nil {
		return
	}
	file_proto_wasmee_proto_msgTypes[0].OneofWrappers = []any{
		(*ExecuteMessage_Start)(nil),
		(*ExecuteMessage_HostCallRequest)(nil),
		(*ExecuteMessage_HostCallResponse)(nil),
		(*ExecuteMessage_Checkpoint)(nil),
		(*ExecuteMessage_CheckpointResponse)(nil),
		(*ExecuteMessage_Complete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wasmee_proto_rawDesc), len(file_proto_wasmee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_wasmee_proto_goTypes,
		DependencyIndexes: file_proto_wasmee_proto_depIdxs,
		MessageInfos:      file_proto_wasmee_proto_msgTypes,
	}.Build()
	File_proto_wasmee_proto = out.File
	file_proto_wasmee_proto_goTypes = nil
	file_proto_wasmee_proto_depIdxs = nil
}
