// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/wasmee.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WasmeeExecutor_Execute_FullMethodName = "/wasmee.WasmeeExecutor/Execute"
)

// WasmeeExecutorClient is the client API for WasmeeExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WasmeeExecutorClient interface {
	Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteMessage, ExecuteMessage], error)
}

type wasmeeExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewWasmeeExecutorClient(cc grpc.ClientConnInterface) WasmeeExecutorClient {
	return &wasmeeExecutorClient{cc}
}

func (c *wasmeeExecutorClient) Execute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecuteMessage, ExecuteMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WasmeeExecutor_ServiceDesc.Streams[0], WasmeeExecutor_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteMessage, ExecuteMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WasmeeExecutor_ExecuteClient = grpc.BidiStreamingClient[ExecuteMessage, ExecuteMessage]

// WasmeeExecutorServer is the server API for WasmeeExecutor service.
// All implementations must embed UnimplementedWasmeeExecutorServer
// for forward compatibility.
type WasmeeExecutorServer interface {
	Execute(grpc.BidiStreamingServer[ExecuteMessage, ExecuteMessage]) error
	mustEmbedUnimplementedWasmeeExecutorServer()
}

// UnimplementedWasmeeExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWasmeeExecutorServer struct{}

func (UnimplementedWasmeeExecutorServer) Execute(grpc.BidiStreamingServer[ExecuteMessage, ExecuteMessage]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedWasmeeExecutorServer) mustEmbedUnimplementedWasmeeExecutorServer() {}
func (UnimplementedWasmeeExecutorServer) testEmbeddedByValue()                        {}

// UnsafeWasmeeExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WasmeeExecutorServer will
// result in compilation errors.
type UnsafeWasmeeExecutorServer interface {
	mustEmbedUnimplementedWasmeeExecutorServer()
}

func RegisterWasmeeExecutorServer(s grpc.ServiceRegistrar, srv WasmeeExecutorServer) {
	// If the following call panics, it indicates UnimplementedWasmeeExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WasmeeExecutor_ServiceDesc, srv)
}

func _WasmeeExecutor_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WasmeeExecutorServer).Execute(&grpc.GenericServerStream[ExecuteMessage, ExecuteMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WasmeeExecutor_ExecuteServer = grpc.BidiStreamingServer[ExecuteMessage, ExecuteMessage]

// WasmeeExecutor_ServiceDesc is the grpc.ServiceDesc for WasmeeExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WasmeeExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wasmee.WasmeeExecutor",
	HandlerType: (*WasmeeExecutorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _WasmeeExecutor_Execute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/wasmee.proto",
}
