// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: wasmee.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OplogEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallIndex       int32                  `protobuf:"varint,1,opt,name=call_index,json=callIndex,proto3" json:"call_index,omitempty"`
	ApiName         string                 `protobuf:"bytes,2,opt,name=api_name,json=apiName,proto3" json:"api_name,omitempty"`
	RequestPayload  []byte                 `protobuf:"bytes,3,opt,name=request_payload,json=requestPayload,proto3" json:"request_payload,omitempty"`
	ResponsePayload []byte                 `protobuf:"bytes,4,opt,name=response_payload,json=responsePayload,proto3" json:"response_payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OplogEntry) Reset() {
	*x = OplogEntry{}
	mi := &file_wasmee_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OplogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OplogEntry) ProtoMessage() {}

func (x *OplogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OplogEntry.ProtoReflect.Descriptor instead.
func (*OplogEntry) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{0}
}

func (x *OplogEntry) GetCallIndex() int32 {
	if x != nil {
		return x.CallIndex
	}
	return 0
}

func (x *OplogEntry) GetApiName() string {
	if x != nil {
		return x.ApiName
	}
	return ""
}

func (x *OplogEntry) GetRequestPayload() []byte {
	if x != nil {
		return x.RequestPayload
	}
	return nil
}

func (x *OplogEntry) GetResponsePayload() []byte {
	if x != nil {
		return x.ResponsePayload
	}
	return nil
}

type GitSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repository    string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	GitRef        string                 `protobuf:"bytes,2,opt,name=git_ref,json=gitRef,proto3" json:"git_ref,omitempty"` // Can be a branch, tag (e.g. v1.0.0), or commit hash
	FilePath      string                 `protobuf:"bytes,3,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	GitToken      string                 `protobuf:"bytes,4,opt,name=git_token,json=gitToken,proto3" json:"git_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSource) Reset() {
	*x = GitSource{}
	mi := &file_wasmee_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSource) ProtoMessage() {}

func (x *GitSource) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSource.ProtoReflect.Descriptor instead.
func (*GitSource) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{1}
}

func (x *GitSource) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *GitSource) GetGitRef() string {
	if x != nil {
		return x.GitRef
	}
	return ""
}

func (x *GitSource) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *GitSource) GetGitToken() string {
	if x != nil {
		return x.GitToken
	}
	return ""
}

type SandboxConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxFuel       uint64                 `protobuf:"varint,1,opt,name=max_fuel,json=maxFuel,proto3" json:"max_fuel,omitempty"`
	MaxMemoryMb   uint32                 `protobuf:"varint,2,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	mi := &file_wasmee_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxConfig.ProtoReflect.Descriptor instead.
func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{2}
}

func (x *SandboxConfig) GetMaxFuel() uint64 {
	if x != nil {
		return x.MaxFuel
	}
	return 0
}

func (x *SandboxConfig) GetMaxMemoryMb() uint32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Entrypoint     string                 `protobuf:"bytes,2,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Params         []uint64               `protobuf:"varint,3,rep,packed,name=params,proto3" json:"params,omitempty"`
	BaseSnapshot   []byte                 `protobuf:"bytes,4,opt,name=base_snapshot,json=baseSnapshot,proto3" json:"base_snapshot,omitempty"`
	MemoryDeltas   map[int32][]byte       `protobuf:"bytes,5,rep,name=memory_deltas,json=memoryDeltas,proto3" json:"memory_deltas,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Oplog          []*OplogEntry          `protobuf:"bytes,6,rep,name=oplog,proto3" json:"oplog,omitempty"`
	ExchangeBuffer []byte                 `protobuf:"bytes,7,opt,name=exchange_buffer,json=exchangeBuffer,proto3" json:"exchange_buffer,omitempty"`
	WasmBytes      []byte                 `protobuf:"bytes,8,opt,name=wasm_bytes,json=wasmBytes,proto3" json:"wasm_bytes,omitempty"`
	WasmHash       string                 `protobuf:"bytes,9,opt,name=wasm_hash,json=wasmHash,proto3" json:"wasm_hash,omitempty"`
	GitSource      *GitSource             `protobuf:"bytes,10,opt,name=git_source,json=gitSource,proto3" json:"git_source,omitempty"`
	SandboxConfig  *SandboxConfig         `protobuf:"bytes,11,opt,name=sandbox_config,json=sandboxConfig,proto3" json:"sandbox_config,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_wasmee_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ExecuteRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *ExecuteRequest) GetParams() []uint64 {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetBaseSnapshot() []byte {
	if x != nil {
		return x.BaseSnapshot
	}
	return nil
}

func (x *ExecuteRequest) GetMemoryDeltas() map[int32][]byte {
	if x != nil {
		return x.MemoryDeltas
	}
	return nil
}

func (x *ExecuteRequest) GetOplog() []*OplogEntry {
	if x != nil {
		return x.Oplog
	}
	return nil
}

func (x *ExecuteRequest) GetExchangeBuffer() []byte {
	if x != nil {
		return x.ExchangeBuffer
	}
	return nil
}

func (x *ExecuteRequest) GetWasmBytes() []byte {
	if x != nil {
		return x.WasmBytes
	}
	return nil
}

func (x *ExecuteRequest) GetWasmHash() string {
	if x != nil {
		return x.WasmHash
	}
	return ""
}

func (x *ExecuteRequest) GetGitSource() *GitSource {
	if x != nil {
		return x.GitSource
	}
	return nil
}

func (x *ExecuteRequest) GetSandboxConfig() *SandboxConfig {
	if x != nil {
		return x.SandboxConfig
	}
	return nil
}

type WarmupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GitSource     *GitSource             `protobuf:"bytes,1,opt,name=git_source,json=gitSource,proto3" json:"git_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmupRequest) Reset() {
	*x = WarmupRequest{}
	mi := &file_wasmee_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmupRequest) ProtoMessage() {}

func (x *WarmupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmupRequest.ProtoReflect.Descriptor instead.
func (*WarmupRequest) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{4}
}

func (x *WarmupRequest) GetGitSource() *GitSource {
	if x != nil {
		return x.GitSource
	}
	return nil
}

type WarmupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WasmHash      string                 `protobuf:"bytes,2,opt,name=wasm_hash,json=wasmHash,proto3" json:"wasm_hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarmupResponse) Reset() {
	*x = WarmupResponse{}
	mi := &file_wasmee_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarmupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarmupResponse) ProtoMessage() {}

func (x *WarmupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarmupResponse.ProtoReflect.Descriptor instead.
func (*WarmupResponse) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{5}
}

func (x *WarmupResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WarmupResponse) GetWasmHash() string {
	if x != nil {
		return x.WasmHash
	}
	return ""
}

func (x *WarmupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CheckpointData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        []byte                 `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	OplogLen      int32                  `protobuf:"varint,2,opt,name=oplog_len,json=oplogLen,proto3" json:"oplog_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointData) Reset() {
	*x = CheckpointData{}
	mi := &file_wasmee_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointData) ProtoMessage() {}

func (x *CheckpointData) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointData.ProtoReflect.Descriptor instead.
func (*CheckpointData) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{6}
}

func (x *CheckpointData) GetMemory() []byte {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *CheckpointData) GetOplogLen() int32 {
	if x != nil {
		return x.OplogLen
	}
	return 0
}

type ExecuteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Crashed        bool                   `protobuf:"varint,1,opt,name=crashed,proto3" json:"crashed,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	FinalDeltas    map[int32][]byte       `protobuf:"bytes,3,rep,name=final_deltas,json=finalDeltas,proto3" json:"final_deltas,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FinalOplog     []*OplogEntry          `protobuf:"bytes,4,rep,name=final_oplog,json=finalOplog,proto3" json:"final_oplog,omitempty"`
	Checkpoints    []*CheckpointData      `protobuf:"bytes,5,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	ResponseBytes  []byte                 `protobuf:"bytes,6,opt,name=response_bytes,json=responseBytes,proto3" json:"response_bytes,omitempty"`
	ModuleNotFound bool                   `protobuf:"varint,7,opt,name=module_not_found,json=moduleNotFound,proto3" json:"module_not_found,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_wasmee_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wasmee_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_wasmee_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteResponse) GetCrashed() bool {
	if x != nil {
		return x.Crashed
	}
	return false
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExecuteResponse) GetFinalDeltas() map[int32][]byte {
	if x != nil {
		return x.FinalDeltas
	}
	return nil
}

func (x *ExecuteResponse) GetFinalOplog() []*OplogEntry {
	if x != nil {
		return x.FinalOplog
	}
	return nil
}

func (x *ExecuteResponse) GetCheckpoints() []*CheckpointData {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

func (x *ExecuteResponse) GetResponseBytes() []byte {
	if x != nil {
		return x.ResponseBytes
	}
	return nil
}

func (x *ExecuteResponse) GetModuleNotFound() bool {
	if x != nil {
		return x.ModuleNotFound
	}
	return false
}

var File_wasmee_proto protoreflect.FileDescriptor

const file_wasmee_proto_rawDesc = "" +
	"\n" +
	"\fwasmee.proto\x12\x06wasmee\"\x9a\x01\n" +
	"\n" +
	"OplogEntry\x12\x1d\n" +
	"\n" +
	"call_index\x18\x01 \x01(\x05R\tcallIndex\x12\x19\n" +
	"\bapi_name\x18\x02 \x01(\tR\aapiName\x12'\n" +
	"\x0frequest_payload\x18\x03 \x01(\fR\x0erequestPayload\x12)\n" +
	"\x10response_payload\x18\x04 \x01(\fR\x0fresponsePayload\"~\n" +
	"\tGitSource\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x12\x17\n" +
	"\agit_ref\x18\x02 \x01(\tR\x06gitRef\x12\x1b\n" +
	"\tfile_path\x18\x03 \x01(\tR\bfilePath\x12\x1b\n" +
	"\tgit_token\x18\x04 \x01(\tR\bgitToken\"N\n" +
	"\rSandboxConfig\x12\x19\n" +
	"\bmax_fuel\x18\x01 \x01(\x04R\amaxFuel\x12\"\n" +
	"\rmax_memory_mb\x18\x02 \x01(\rR\vmaxMemoryMb\"\x9d\x04\n" +
	"\x0eExecuteRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x02 \x01(\tR\n" +
	"entrypoint\x12\x16\n" +
	"\x06params\x18\x03 \x03(\x04R\x06params\x12#\n" +
	"\rbase_snapshot\x18\x04 \x01(\fR\fbaseSnapshot\x12M\n" +
	"\rmemory_deltas\x18\x05 \x03(\v2(.wasmee.ExecuteRequest.MemoryDeltasEntryR\fmemoryDeltas\x12(\n" +
	"\x05oplog\x18\x06 \x03(\v2\x12.wasmee.OplogEntryR\x05oplog\x12'\n" +
	"\x0fexchange_buffer\x18\a \x01(\fR\x0eexchangeBuffer\x12\x1d\n" +
	"\n" +
	"wasm_bytes\x18\b \x01(\fR\twasmBytes\x12\x1b\n" +
	"\twasm_hash\x18\t \x01(\tR\bwasmHash\x120\n" +
	"\n" +
	"git_source\x18\n" +
	" \x01(\v2\x11.wasmee.GitSourceR\tgitSource\x12<\n" +
	"\x0esandbox_config\x18\v \x01(\v2\x15.wasmee.SandboxConfigR\rsandboxConfig\x1a?\n" +
	"\x11MemoryDeltasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"A\n" +
	"\rWarmupRequest\x120\n" +
	"\n" +
	"git_source\x18\x01 \x01(\v2\x11.wasmee.GitSourceR\tgitSource\"]\n" +
	"\x0eWarmupResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\twasm_hash\x18\x02 \x01(\tR\bwasmHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"E\n" +
	"\x0eCheckpointData\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\fR\x06memory\x12\x1b\n" +
	"\toplog_len\x18\x02 \x01(\x05R\boplogLen\"\x8e\x03\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\acrashed\x18\x01 \x01(\bR\acrashed\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12K\n" +
	"\ffinal_deltas\x18\x03 \x03(\v2(.wasmee.ExecuteResponse.FinalDeltasEntryR\vfinalDeltas\x123\n" +
	"\vfinal_oplog\x18\x04 \x03(\v2\x12.wasmee.OplogEntryR\n" +
	"finalOplog\x128\n" +
	"\vcheckpoints\x18\x05 \x03(\v2\x16.wasmee.CheckpointDataR\vcheckpoints\x12%\n" +
	"\x0eresponse_bytes\x18\x06 \x01(\fR\rresponseBytes\x12(\n" +
	"\x10module_not_found\x18\a \x01(\bR\x0emoduleNotFound\x1a>\n" +
	"\x10FinalDeltasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01B Z\x1egithub.com/nativebpm/wasmee/pbb\x06proto3"

var (
	file_wasmee_proto_rawDescOnce sync.Once
	file_wasmee_proto_rawDescData []byte
)

func file_wasmee_proto_rawDescGZIP() []byte {
	file_wasmee_proto_rawDescOnce.Do(func() {
		file_wasmee_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wasmee_proto_rawDesc), len(file_wasmee_proto_rawDesc)))
	})
	return file_wasmee_proto_rawDescData
}

var file_wasmee_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wasmee_proto_goTypes = []any{
	(*OplogEntry)(nil),      // 0: wasmee.OplogEntry
	(*GitSource)(nil),       // 1: wasmee.GitSource
	(*SandboxConfig)(nil),   // 2: wasmee.SandboxConfig
	(*ExecuteRequest)(nil),  // 3: wasmee.ExecuteRequest
	(*WarmupRequest)(nil),   // 4: wasmee.WarmupRequest
	(*WarmupResponse)(nil),  // 5: wasmee.WarmupResponse
	(*CheckpointData)(nil),  // 6: wasmee.CheckpointData
	(*ExecuteResponse)(nil), // 7: wasmee.ExecuteResponse
	nil,                     // 8: wasmee.ExecuteRequest.MemoryDeltasEntry
	nil,                     // 9: wasmee.ExecuteResponse.FinalDeltasEntry
}
var file_wasmee_proto_depIdxs = []int32{
	8, // 0: wasmee.ExecuteRequest.memory_deltas:type_name -> wasmee.ExecuteRequest.MemoryDeltasEntry
	0, // 1: wasmee.ExecuteRequest.oplog:type_name -> wasmee.OplogEntry
	1, // 2: wasmee.ExecuteRequest.git_source:type_name -> wasmee.GitSource
	2, // 3: wasmee.ExecuteRequest.sandbox_config:type_name -> wasmee.SandboxConfig
	1, // 4: wasmee.WarmupRequest.git_source:type_name -> wasmee.GitSource
	9, // 5: wasmee.ExecuteResponse.final_deltas:type_name -> wasmee.ExecuteResponse.FinalDeltasEntry
	0, // 6: wasmee.ExecuteResponse.final_oplog:type_name -> wasmee.OplogEntry
	6, // 7: wasmee.ExecuteResponse.checkpoints:type_name -> wasmee.CheckpointData
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_wasmee_proto_init() }
func file_wasmee_proto_init() {
	if File_wasmee_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wasmee_proto_rawDesc), len(file_wasmee_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wasmee_proto_goTypes,
		DependencyIndexes: file_wasmee_proto_depIdxs,
		MessageInfos:      file_wasmee_proto_msgTypes,
	}.Build()
	File_wasmee_proto = out.File
	file_wasmee_proto_goTypes = nil
	file_wasmee_proto_depIdxs = nil
}
